# Generated by Django 4.2.7 on 2023-11-26 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MosTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='制作日')),
                ('updated_by', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('test_name', models.CharField(max_length=100, verbose_name='テスト名')),
                ('description', models.TextField(blank=True, verbose_name='テストの説明')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Acoustic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acoustic_model_name', models.CharField(max_length=100, verbose_name='音響モデル名')),
                ('audio', models.FileField(upload_to='audios/')),
                ('mos_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.mostest')),
            ],
        ),
    ]
