# Generated by Django 4.2.7 on 2023-11-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoustic',
            name='audio',
            field=models.FileField(upload_to='file/%Y/%m/%d'),
        ),
    ]
