# Generated by Django 4.2.7 on 2023-11-29 06:00

from django.db import migrations, models
import testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_acoustic_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoustic',
            name='audio',
            field=models.FileField(upload_to=testapp.models.Acoustic.user_directory_path),
        ),
    ]
