# Generated by Django 4.2.7 on 2023-12-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_acoustic_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostest',
            name='instruction',
            field=models.TextField(blank=True, verbose_name='テストの指示'),
        ),
        migrations.AlterField(
            model_name='mostest',
            name='description',
            field=models.TextField(blank=True, verbose_name='テストの概要'),
        ),
    ]
