# Generated by Django 4.2.7 on 2023-12-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_mostest_instruction_alter_mostest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='テストの概要'),
        ),
        migrations.AlterField(
            model_name='mostest',
            name='instruction',
            field=models.TextField(blank=True, null=True, verbose_name='テストの指示'),
        ),
    ]
