# Generated by Django 4.2.17 on 2025-01-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_mostest_description_alter_mostest_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='acoustic',
            name='text',
            field=models.CharField(default='no_text', max_length=100, verbose_name='テキスト'),
            preserve_default=False,
        ),
    ]
