# Generated by Django 4.2.17 on 2025-01-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acousticapp', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='target_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='[音声のトランスクリプトをここに記入]'),
        ),
    ]
