# Generated by Django 4.2.17 on 2025-01-06 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acousticapp', '0005_answer_target_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='target_text',
        ),
    ]
