# Generated by Django 5.1.4 on 2025-01-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acousticapp', '0006_remove_answer_target_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='mos',
            field=models.IntegerField(choices=[(None, '選択してください'), (1, '1 - 非常に不自然(bad)'), (2, '2 - 不自然(poor)'), (3, '3 - 普通(fair)'), (4, '4 - 自然(good)'), (5, '5 - 非常に自然(excellent)')]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='気づいたこと、疑問点、改善点ありましたらコメントお願いします。'),
        ),
    ]
